apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
      receiver: 'local-test-webhook'

    receivers:
      - name: 'local-test-webhook'
        webhook_configs:
          - url: 'http://webhook-service.monitoring.svc.cluster.local:9000/alerts'
            send_resolved: true